const Primary_theme = {
  primaryDark: '#0A1128',
  primaryLight: '#1A2980',
  secondary: '#00b09b',
  white: '#ffffff',
  lightGray: '#e6e6e6',
  red: '#ff5252',
  gradientStart: '#0A1128',
  gradientEnd: '#1A2980',
  buttonBackground: '#00b09b',
  buttonText: '#ffffff',
  textPrimary: '#ffffff',
  textSecondary: '#e6e6e6',
  navBarBackground: '#0A1128',
  iconColor: '#ffffff',
  navBarIconColor: 'black',
  gradientstartlogin: '#0A1128',
  gradientendlogin: '#1A2980',
};

const Secondary_theme = {
  primaryDark: '#ffffff',
  primaryLight: '#f8f9fa',
  secondary: '#009B3A',
  white: '#ffffff',
  lightGray: '#f0f0f0',
  red: '#e53935',
  gradientStart: '#ffffff',
  gradientEnd: '#f8f9fa',
  buttonBackground: '#009B3A',
  buttonText: 'white',
  textPrimary: '#212121',
  textSecondary: '#424242',
  iconColor: 'black',
  navBarIconColor: 'black',
  gradientstartlogin: '#009B3A',
  gradientendlogin: '#f8f9fa',
};

const Tertiary_theme = {
  primaryDark: '#121212',
  primaryLight: '#1e1e1e',
  secondary: '#009B3A',
  white: '#ffffff',
  lightGray: '#757575',
  red: '#f44336',
  gradientStart: '#121212',
  gradientEnd: '#1e1e1e',
  buttonBackground: '#009B3A', 
  buttonText: '#ffffff',
  textPrimary: '#ffffff',
  textSecondary: '#e0e0e0',
  navBarBackground: '#1e1e1e',
  iconColor: '#009B3A', 
  navBarIconColor: 'black',
  gradientstartlogin: '#009B3A', 
  gradientendlogin: '#1e1e1e',
};

export { Primary_theme, Secondary_theme, Tertiary_theme };
